name: Terraform GitOps Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform_deployment:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan -var="s3_bucket_name=gitops-automation-bucket"

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform plan -var="s3_bucket_name=gitops-automation-bucket"
